import type {
  AccountData,
  Agent,
  AnalyticsData,
  BillingData,
  Conversation,
  DashboardData,
  Integration,
  KnowledgeSource,
  NotificationItem,
  SettingsData,
  SupportData,
  WorkspaceSnapshot,
  WorkspaceUser,
} from "@/types/workspace";

const agents: Agent[] = [
  {
    id: "agent-manager",
    name: "Ava Mercer",
    role: "Agent Manager",
    personality:
      "Calm, executive, and deeply operational. Balances strategic direction with hands-on supervision.",
    summary:
      "Oversees the digital workforce, flags operational risks, and coordinates handoffs across the team.",
    avatar: "AM",
    status: "active",
    connectedChannels: 6,
    connectedTools: 9,
    pendingWork: 4,
    recentActivity: "Escalated an approval request for a pricing exception 9 minutes ago.",
    nextAction: "Review unresolved support backlog and propose staffing adjustments.",
    approvalsNeeded: 2,
    performance: {
      resolutionRate: "94%",
      responseTime: "2m",
      qualityScore: "9.4/10",
      approvalsNeeded: "4 today",
    },
    channels: ["Executive chat", "Slack", "Gmail", "WhatsApp", "CRM", "Analytics"],
    tools: ["Approvals", "Team summaries", "Conversation search", "Playbooks"],
    permissions: ["Supervise all agents", "Recommend staffing", "Request approvals"],
    knows: [
      "Pricing policy",
      "Escalation matrix",
      "Enterprise support playbooks",
      "Q2 revenue targets",
    ],
    identity: {
      mission: "Keep the AI workforce aligned, safe, and accountable.",
      style: "Direct, measured, concise, and audit-friendly.",
      supervision: "Requires human approval for policy, pricing, and compliance-sensitive actions.",
    },
    activity: [
      {
        id: "am-1",
        title: "Recommended sales coverage shift",
        detail: "Suggested routing two mid-market inbound threads to the Sales Agent.",
        timestamp: "9m ago",
        actor: "Ava Mercer",
        tone: "success",
      },
      {
        id: "am-2",
        title: "Flagged knowledge gap",
        detail: "Detected missing refund policy updates in support training materials.",
        timestamp: "26m ago",
        actor: "Ava Mercer",
        tone: "warning",
      },
      {
        id: "am-3",
        title: "Prepared executive summary",
        detail: "Shared morning workforce briefing with unresolved approvals and sync health.",
        timestamp: "1h ago",
        actor: "Ava Mercer",
      },
    ],
    pendingTasks: [
      {
        id: "am-task-1",
        title: "Review pricing exception escalation",
        status: "awaiting_approval",
        dueLabel: "Due in 20m",
      },
      {
        id: "am-task-2",
        title: "Refresh support workload recommendation",
        status: "in_progress",
        dueLabel: "Running now",
      },
    ],
    trainingHistory: [
      {
        id: "am-tr-1",
        title: "Added escalation policy v3",
        detail: "Updated approval thresholds for discount approvals over 18%.",
        timestamp: "Yesterday",
      },
      {
        id: "am-tr-2",
        title: "Leadership tone adjustment",
        detail: "Reduced urgency language for executive summaries after 6pm local time.",
        timestamp: "3 days ago",
      },
    ],
    messages: [
      {
        id: "am-msg-1",
        author: "Ava Mercer",
        senderType: "agent",
        body: "I have two operational concerns today: a support knowledge gap around refund policy updates, and one pricing approval blocking a sales follow-up.",
        timestamp: "09:02",
        status: "delivered",
      },
      {
        id: "am-msg-2",
        author: "You",
        senderType: "user",
        body: "Summarize the highest-risk issue in the next hour.",
        timestamp: "09:04",
        status: "sent",
      },
      {
        id: "am-msg-3",
        author: "Ava Mercer",
        senderType: "agent",
        body: "The highest-risk issue is the pricing exception. If it remains unresolved, we likely lose momentum on a qualified mid-market opportunity currently waiting in Sales.",
        timestamp: "09:04",
        status: "delivered",
      },
    ],
  },
  {
    id: "secretary-agent",
    name: "Mila Hart",
    role: "Secretary Agent",
    personality:
      "Warm, polished, and detail-oriented. Optimizes schedules, notes, and follow-through without noise.",
    summary:
      "Handles executive scheduling, inbox triage, meeting prep, and follow-up coordination.",
    avatar: "MH",
    status: "active",
    connectedChannels: 4,
    connectedTools: 6,
    pendingWork: 8,
    recentActivity: "Rescheduled a customer onboarding review and updated meeting notes.",
    nextAction: "Draft an internal brief for tomorrow's leadership meeting.",
    approvalsNeeded: 0,
    performance: {
      resolutionRate: "97%",
      responseTime: "1.4m",
      qualityScore: "9.6/10",
      approvalsNeeded: "0 today",
    },
    channels: ["Gmail", "Calendar", "Slack", "Docs"],
    tools: ["Calendar", "Meeting notes", "Inbox triage", "Drafts"],
    permissions: ["Draft messages", "Manage schedules", "Share summaries"],
    knows: ["Meeting templates", "Leadership preferences", "Travel policies"],
    identity: {
      mission: "Reduce coordination overhead for leaders and teams.",
      style: "Polished, precise, and quietly proactive.",
      supervision: "Can draft and schedule autonomously, but external commitments require visibility.",
    },
    activity: [
      {
        id: "se-1",
        title: "Prepared meeting brief",
        detail: "Compiled participants, agenda, and open decisions for customer renewal review.",
        timestamp: "14m ago",
        actor: "Mila Hart",
      },
      {
        id: "se-2",
        title: "Inbox triage complete",
        detail: "Sorted 27 executive messages into replies, FYI, and scheduling actions.",
        timestamp: "48m ago",
        actor: "Mila Hart",
        tone: "success",
      },
    ],
    pendingTasks: [
      {
        id: "se-task-1",
        title: "Send revised agenda to onboarding team",
        status: "queued",
        dueLabel: "Due in 1h",
      },
    ],
    trainingHistory: [
      {
        id: "se-tr-1",
        title: "Added executive scheduling preferences",
        detail: "Avoids external calls on Friday afternoons unless marked urgent.",
        timestamp: "2 days ago",
      },
    ],
    messages: [
      {
        id: "se-msg-1",
        author: "Mila Hart",
        senderType: "agent",
        body: "I have already reorganized tomorrow's leadership agenda. Do you want the revised attendee notes as a short brief or a full packet?",
        timestamp: "08:52",
        status: "delivered",
      },
    ],
  },
  {
    id: "support-agent",
    name: "Jonah Vale",
    role: "Support Agent",
    personality:
      "Patient, calm under pressure, and meticulous with edge cases and approvals.",
    summary:
      "Owns support conversations, triages escalations, and keeps service quality consistent.",
    avatar: "JV",
    status: "awaiting_approval",
    connectedChannels: 5,
    connectedTools: 7,
    pendingWork: 13,
    recentActivity: "Paused a refund-related response pending policy clarification.",
    nextAction: "Resume two escalated threads once refund guidance is approved.",
    approvalsNeeded: 3,
    performance: {
      resolutionRate: "88%",
      responseTime: "4.8m",
      qualityScore: "9.1/10",
      approvalsNeeded: "3 today",
    },
    channels: ["Email", "Slack", "WhatsApp", "Helpdesk", "CRM"],
    tools: ["Macros", "Help center", "Escalations", "Refund policy"],
    permissions: ["Resolve level 1 support", "Request refunds", "Escalate policy issues"],
    knows: ["Support playbooks", "Product FAQ", "Known incidents", "SLA policy"],
    identity: {
      mission: "Protect customer trust while maintaining response discipline.",
      style: "Empathetic, calm, and policy-aware.",
      supervision: "Needs approval for refunds, credits, or high-risk exceptions.",
    },
    activity: [
      {
        id: "su-1",
        title: "Awaiting policy confirmation",
        detail: "Paused three refund responses because uploaded policy coverage is outdated.",
        timestamp: "6m ago",
        actor: "Jonah Vale",
        tone: "warning",
      },
      {
        id: "su-2",
        title: "Resolved deployment concern",
        detail: "Closed a multi-channel onboarding incident within target SLA.",
        timestamp: "52m ago",
        actor: "Jonah Vale",
        tone: "success",
      },
    ],
    pendingTasks: [
      {
        id: "su-task-1",
        title: "Approve refund response language",
        status: "awaiting_approval",
        dueLabel: "Waiting on policy owner",
      },
      {
        id: "su-task-2",
        title: "Follow up on unresolved onboarding issue",
        status: "in_progress",
        dueLabel: "Due in 35m",
      },
    ],
    trainingHistory: [
      {
        id: "su-tr-1",
        title: "Added updated escalation matrix",
        detail: "Changed financial exceptions to human approval only.",
        timestamp: "Yesterday",
      },
    ],
    messages: [
      {
        id: "su-msg-1",
        author: "Jonah Vale",
        senderType: "agent",
        body: "I can continue with the customer apology and resolution path, but I need approval on the refund wording before sending.",
        timestamp: "09:10",
        status: "pending",
      },
    ],
  },
  {
    id: "sales-agent",
    name: "Nora Ellis",
    role: "Sales Agent",
    personality:
      "Confident, consultative, and disciplined about qualification and timing.",
    summary:
      "Runs inbound qualification, follow-ups, pricing coordination, and meeting booking.",
    avatar: "NE",
    status: "active",
    connectedChannels: 4,
    connectedTools: 8,
    pendingWork: 6,
    recentActivity: "Qualified two enterprise leads and opened one pricing approval request.",
    nextAction: "Follow up with a procurement stakeholder after approval lands.",
    approvalsNeeded: 1,
    performance: {
      resolutionRate: "91%",
      responseTime: "3.1m",
      qualityScore: "9.3/10",
      approvalsNeeded: "1 today",
    },
    channels: ["Email", "CRM", "Calendar", "Slack"],
    tools: ["Lead scoring", "Sequences", "Pricing approvals", "Call notes"],
    permissions: ["Qualify leads", "Schedule demos", "Request pricing"],
    knows: ["ICP definitions", "Pricing guide", "Case studies", "Competitor notes"],
    identity: {
      mission: "Convert qualified demand without sacrificing precision or brand trust.",
      style: "Concise, commercially sharp, and helpful.",
      supervision: "Requires approval for pricing exceptions and enterprise legal statements.",
    },
    activity: [
      {
        id: "sa-1",
        title: "Opened pricing exception",
        detail: "Requested review for a 14-seat pilot with custom onboarding terms.",
        timestamp: "11m ago",
        actor: "Nora Ellis",
        tone: "warning",
      },
      {
        id: "sa-2",
        title: "Booked discovery call",
        detail: "Secured a Tuesday meeting with a regional operations VP.",
        timestamp: "37m ago",
        actor: "Nora Ellis",
        tone: "success",
      },
    ],
    pendingTasks: [
      {
        id: "sa-task-1",
        title: "Deliver approved commercial summary",
        status: "awaiting_approval",
        dueLabel: "Waiting on manager",
      },
      {
        id: "sa-task-2",
        title: "Prepare prospect recap email",
        status: "queued",
        dueLabel: "Due in 50m",
      },
    ],
    trainingHistory: [
      {
        id: "sa-tr-1",
        title: "Adjusted qualification rubric",
        detail: "Increased weight for multi-channel support and compliance needs.",
        timestamp: "4 days ago",
      },
    ],
    messages: [
      {
        id: "sa-msg-1",
        author: "Nora Ellis",
        senderType: "agent",
        body: "The lead is strong. I recommend approving the pricing exception with onboarding scoped to one admin team and one shared inbox.",
        timestamp: "09:08",
        status: "delivered",
      },
    ],
  },
  {
    id: "cs-agent",
    name: "Elena Shore",
    role: "Customer Success Agent",
    personality:
      "Measured, relational, and proactive about adoption risks and renewal timing.",
    summary:
      "Supports onboarding, adoption, renewals, and early risk detection for customer accounts.",
    avatar: "ES",
    status: "training",
    connectedChannels: 4,
    connectedTools: 5,
    pendingWork: 5,
    recentActivity: "Reviewed three adoption signals and flagged one declining workspace.",
    nextAction: "Draft a recovery plan for an at-risk onboarding account.",
    approvalsNeeded: 1,
    performance: {
      resolutionRate: "89%",
      responseTime: "5.2m",
      qualityScore: "9.0/10",
      approvalsNeeded: "1 today",
    },
    channels: ["Email", "Slack", "CRM", "Docs"],
    tools: ["Health score", "Onboarding checklists", "Renewal briefs"],
    permissions: ["Send check-ins", "Escalate risks", "Coordinate onboarding"],
    knows: ["Renewal framework", "Success plans", "Implementation guides"],
    identity: {
      mission: "Protect adoption and retention through disciplined follow-up.",
      style: "Supportive, observant, and concise.",
      supervision: "Currently in supervised training for high-risk renewal interactions.",
    },
    activity: [
      {
        id: "cs-1",
        title: "Entered supervised mode",
        detail: "Awaiting signoff on an at-risk account recovery plan.",
        timestamp: "18m ago",
        actor: "Elena Shore",
        tone: "warning",
      },
    ],
    pendingTasks: [
      {
        id: "cs-task-1",
        title: "Review customer recovery plan",
        status: "awaiting_approval",
        dueLabel: "Due in 30m",
      },
    ],
    trainingHistory: [
      {
        id: "cs-tr-1",
        title: "Uploaded renewal objection notes",
        detail: "Added language for adoption blockers and rollout pacing.",
        timestamp: "Today",
      },
    ],
    messages: [
      {
        id: "cs-msg-1",
        author: "Elena Shore",
        senderType: "agent",
        body: "I detected a drop in usage from the rollout owner. I have a draft recovery plan ready for review.",
        timestamp: "08:58",
        status: "delivered",
      },
    ],
  },
  {
    id: "recruiter-agent",
    name: "Theo Quinn",
    role: "Recruiter Agent",
    personality:
      "Organized, professional, and fast at keeping candidate communication moving.",
    summary:
      "Coordinates candidate communication, screening notes, scheduling, and pipeline hygiene.",
    avatar: "TQ",
    status: "active",
    connectedChannels: 3,
    connectedTools: 6,
    pendingWork: 7,
    recentActivity: "Moved two candidates to manager review and booked a panel interview.",
    nextAction: "Send personalized follow-up to one shortlisted operations candidate.",
    approvalsNeeded: 0,
    performance: {
      resolutionRate: "95%",
      responseTime: "2.7m",
      qualityScore: "9.2/10",
      approvalsNeeded: "0 today",
    },
    channels: ["ATS", "Email", "Calendar"],
    tools: ["Candidate notes", "Interview scheduling", "Pipeline summary"],
    permissions: ["Advance pipeline", "Draft outreach", "Schedule interviews"],
    knows: ["Hiring scorecards", "Role profiles", "Interview rubrics"],
    identity: {
      mission: "Keep hiring processes moving without losing candidate quality.",
      style: "Professional, prompt, and structured.",
      supervision: "Can coordinate routine recruiting activity autonomously.",
    },
    activity: [
      {
        id: "rq-1",
        title: "Advanced pipeline",
        detail: "Moved two candidates into final manager review with updated notes.",
        timestamp: "23m ago",
        actor: "Theo Quinn",
        tone: "success",
      },
    ],
    pendingTasks: [
      {
        id: "rq-task-1",
        title: "Send panel interview brief",
        status: "queued",
        dueLabel: "Due in 45m",
      },
    ],
    trainingHistory: [
      {
        id: "rq-tr-1",
        title: "Updated outreach voice",
        detail: "Shifted to a more direct tone for senior-level candidates.",
        timestamp: "1 week ago",
      },
    ],
    messages: [
      {
        id: "rq-msg-1",
        author: "Theo Quinn",
        senderType: "agent",
        body: "The operations candidate is strong and likely ready for final review. I can send the interview brief now.",
        timestamp: "08:44",
        status: "delivered",
      },
    ],
  },
];

const conversations: Conversation[] = [
  {
    id: "conv-1",
    subject: "Refund clarification for onboarding delay",
    channel: "Email",
    customer: "Harbor North Logistics",
    assignedAgentId: "support-agent",
    assignedAgentName: "Jonah Vale",
    status: "awaiting_approval",
    priority: "high",
    lastMessage: "Awaiting approved refund wording before reply.",
    lastUpdated: "7m ago",
    notes: [
      "Customer is sensitive to rollout timing.",
      "Finance approval required for any credit.",
    ],
    needsApproval: true,
    thread: [
      {
        id: "conv-1-1",
        author: "Customer",
        senderType: "user",
        body: "We need confirmation on whether your team can offer a service credit after the onboarding delays.",
        timestamp: "08:51",
      },
      {
        id: "conv-1-2",
        author: "Jonah Vale",
        senderType: "agent",
        body: "I have a response drafted, but I’m holding it until approval is granted for the refund-related language.",
        timestamp: "09:09",
        status: "pending",
      },
    ],
  },
  {
    id: "conv-2",
    subject: "Enterprise pilot pricing review",
    channel: "Email",
    customer: "Vectorlane",
    assignedAgentId: "sales-agent",
    assignedAgentName: "Nora Ellis",
    status: "open",
    priority: "critical",
    lastMessage: "Pricing exception submitted for manager review.",
    lastUpdated: "10m ago",
    notes: ["High-intent lead", "Needs procurement-friendly summary"],
    needsApproval: true,
    thread: [
      {
        id: "conv-2-1",
        author: "Nora Ellis",
        senderType: "agent",
        body: "I’ve positioned the pilot around shared support and one manager admin group. Waiting on approval to send final numbers.",
        timestamp: "09:05",
      },
    ],
  },
  {
    id: "conv-3",
    subject: "Candidate panel scheduling",
    channel: "ATS",
    customer: "Operations Candidate",
    assignedAgentId: "recruiter-agent",
    assignedAgentName: "Theo Quinn",
    status: "resolved",
    priority: "medium",
    lastMessage: "Panel interview confirmed for Tuesday.",
    lastUpdated: "31m ago",
    notes: ["Panel pack shared internally"],
    needsApproval: false,
    thread: [
      {
        id: "conv-3-1",
        author: "Theo Quinn",
        senderType: "agent",
        body: "Interview slots are confirmed and the candidate has accepted the calendar invitation.",
        timestamp: "08:39",
      },
    ],
  },
  {
    id: "conv-4",
    subject: "Onboarding adoption risk",
    channel: "Slack",
    customer: "Northstar Retail",
    assignedAgentId: "cs-agent",
    assignedAgentName: "Elena Shore",
    status: "escalated",
    priority: "high",
    lastMessage: "Usage dip flagged and recovery plan drafted.",
    lastUpdated: "19m ago",
    notes: ["Low workspace engagement", "Manager visibility required"],
    needsApproval: true,
    thread: [
      {
        id: "conv-4-1",
        author: "Elena Shore",
        senderType: "agent",
        body: "Adoption signals dropped over the last 48 hours. I have a recommended recovery plan ready for approval.",
        timestamp: "08:57",
      },
    ],
  },
];

const knowledge: KnowledgeSource[] = [
  {
    id: "source-1",
    title: "Refund Policy v3",
    type: "doc",
    status: "processing",
    updatedAt: "12m ago",
    owner: "Operations",
    summary: "Updated policy draft covering service credits, edge cases, and approval rules.",
    coverage: "Support, Agent Manager",
    accessibleAgentIds: ["support-agent", "agent-manager"],
    sizeLabel: "18 pages",
    detail:
      "Pending ingestion. Support approvals remain partially blocked until the updated service credit section completes processing.",
  },
  {
    id: "source-2",
    title: "Enterprise Pricing Guide",
    type: "file",
    status: "ready",
    updatedAt: "Yesterday",
    owner: "Revenue Ops",
    summary: "Commercial packaging, discount thresholds, and procurement notes.",
    coverage: "Sales, Agent Manager",
    accessibleAgentIds: ["sales-agent", "agent-manager"],
    sizeLabel: "PDF",
    detail:
      "Current pricing source for pilot and enterprise conversations, including approval thresholds and package boundaries.",
  },
  {
    id: "source-3",
    title: "Onboarding FAQ",
    type: "faq",
    status: "ready",
    updatedAt: "2 days ago",
    owner: "Customer Success",
    summary: "Common onboarding questions, deployment sequencing, and adoption guidance.",
    coverage: "Customer Success, Support",
    accessibleAgentIds: ["cs-agent", "support-agent"],
    sizeLabel: "42 entries",
    detail:
      "Frequently used during implementation and adoption outreach. Search coverage is healthy with no conflicts detected.",
  },
  {
    id: "source-4",
    title: "Recruiting Screen Recording",
    type: "video",
    status: "attention_needed",
    updatedAt: "3h ago",
    owner: "Talent",
    summary: "Recorded walkthrough of the interview scorecard process.",
    coverage: "Recruiter",
    accessibleAgentIds: ["recruiter-agent"],
    sizeLabel: "24 min",
    detail:
      "Transcript quality is low in two sections. Recruiter guidance is usable, but confidence is reduced for detailed policy references.",
  },
  {
    id: "source-5",
    title: "Executive Daily Brief Prompt",
    type: "chat",
    status: "ready",
    updatedAt: "Today",
    owner: "Leadership",
    summary: "Structured prompt and formatting guidance for the Agent Manager narrative summary.",
    coverage: "Agent Manager",
    accessibleAgentIds: ["agent-manager"],
    sizeLabel: "Template",
    detail:
      "Used by the Agent Manager to produce concise executive briefings with risk-first prioritization.",
  },
];

const integrations: Integration[] = [
  {
    id: "gmail",
    name: "Gmail",
    category: "native",
    status: "connected",
    ownership: "shared",
    authType: "OAuth",
    lastSync: "2m ago",
    accessLevel: "Workspace mailboxes",
    assignedAgentIds: ["secretary-agent", "support-agent", "sales-agent"],
    description: "Shared email access for inbox triage, support, scheduling, and sales follow-up.",
    actions: ["Reconnect", "Audit access", "Assign agents"],
  },
  {
    id: "slack",
    name: "Slack",
    category: "native",
    status: "connected",
    ownership: "shared",
    authType: "OAuth",
    lastSync: "1m ago",
    accessLevel: "Workspace channels",
    assignedAgentIds: ["agent-manager", "support-agent", "cs-agent"],
    description: "Internal and customer-facing Slack channels with scoped posting rules.",
    actions: ["Manage channels", "Review scopes"],
  },
  {
    id: "ats",
    name: "ATS",
    category: "custom_api",
    status: "connected",
    ownership: "private",
    authType: "API key",
    lastSync: "9m ago",
    accessLevel: "Recruiting pipeline",
    assignedAgentIds: ["recruiter-agent"],
    description: "Private recruiting integration for candidate pipeline and interview coordination.",
    actions: ["Rotate key", "Test sync"],
  },
  {
    id: "crm",
    name: "CRM",
    category: "custom_api",
    status: "syncing",
    ownership: "shared",
    authType: "OpenAPI import",
    lastSync: "Running now",
    accessLevel: "Revenue workspace",
    assignedAgentIds: ["sales-agent", "cs-agent", "agent-manager"],
    description: "Customer and pipeline system with recent schema refresh in progress.",
    actions: ["Open logs", "Re-run import"],
  },
  {
    id: "mcp-server",
    name: "MCP Server",
    category: "mcp",
    status: "attention",
    ownership: "private",
    authType: "Server token",
    lastSync: "47m ago",
    accessLevel: "Selected internal tools",
    assignedAgentIds: ["agent-manager"],
    description: "Private MCP connection exposing internal reporting and audit endpoints.",
    actions: ["Reconnect", "View permissions"],
  },
];

const users: WorkspaceUser[] = [
  {
    id: "user-1",
    name: "Oscar Fernandez",
    email: "oscar@example.com",
    role: "admin",
    status: "active",
    lastActive: "Now",
    permissionsSummary: "Full workspace administration, billing, and supervision.",
  },
  {
    id: "user-2",
    name: "Priya Shah",
    email: "priya@example.com",
    role: "manager",
    status: "active",
    lastActive: "12m ago",
    permissionsSummary: "Can supervise agents, manage approvals, and view analytics.",
  },
  {
    id: "user-3",
    name: "Marco Lee",
    email: "marco@example.com",
    role: "human_agent",
    status: "active",
    lastActive: "47m ago",
    permissionsSummary: "Can join handoffs, add notes, and handle escalated conversations.",
  },
  {
    id: "user-4",
    name: "Dana Brooks",
    email: "dana@example.com",
    role: "viewer",
    status: "inactive",
    lastActive: "3 days ago",
    permissionsSummary: "Read-only visibility into dashboard and analytics.",
  },
];

const notifications: NotificationItem[] = [
  {
    id: "notif-1",
    title: "Pricing approval requested",
    description: "Sales Agent needs approval to send a pilot pricing exception to Vectorlane.",
    category: "approval",
    createdAt: "8m ago",
    unread: true,
    actionLabel: "Review request",
  },
  {
    id: "notif-2",
    title: "Knowledge processing still running",
    description: "Refund Policy v3 has not finished ingestion. Support approvals remain partially blocked.",
    category: "knowledge",
    createdAt: "14m ago",
    unread: true,
    actionLabel: "Open source",
  },
  {
    id: "notif-3",
    title: "MCP integration needs attention",
    description: "The private MCP Server has not synced successfully for 47 minutes.",
    category: "integration",
    createdAt: "47m ago",
    unread: false,
    actionLabel: "Inspect integration",
  },
];

const dashboard: DashboardData = {
  managerNarrative:
    "Your AI workforce is operating steadily, but two issues need manager attention this morning: one pricing exception is blocking a high-intent sales thread, and support guidance for refunds is still catching up to the latest policy upload.",
  overview: [
    {
      label: "Active agents",
      value: "6",
      change: "+1 this quarter",
      tone: "success",
      description: "All core business roles are staffed.",
    },
    {
      label: "Pending actions",
      value: "18",
      change: "4 need approval",
      tone: "warning",
      description: "Mostly support and sales follow-through.",
    },
    {
      label: "Live conversations",
      value: "27",
      change: "+6 since 8am",
      tone: "neutral",
      description: "Open threads across email, Slack, ATS, and WhatsApp.",
    },
  ],
  healthIndicators: [
    {
      label: "Team coverage",
      value: "Healthy",
      tone: "success",
      hint: "All critical functions staffed and active.",
    },
    {
      label: "Approvals queue",
      value: "Needs review",
      tone: "warning",
      hint: "Four items are waiting on a manager decision.",
    },
    {
      label: "Knowledge freshness",
      value: "Partial gap",
      tone: "warning",
      hint: "Refund policy ingestion is still running.",
    },
    {
      label: "Integrations",
      value: "One issue",
      tone: "warning",
      hint: "Private MCP connection needs inspection.",
    },
  ],
  approvals: [
    {
      id: "approval-1",
      title: "Approve pricing exception",
      detail: "Vectorlane pilot requires approval before Sales can send final proposal.",
      owner: "Nora Ellis",
      priority: "critical",
      dueLabel: "Due in 18m",
    },
    {
      id: "approval-2",
      title: "Approve refund response",
      detail: "Support refund wording is blocked until policy coverage is confirmed.",
      owner: "Jonah Vale",
      priority: "high",
      dueLabel: "Due in 24m",
    },
  ],
  unresolvedConversations: conversations.filter(
    (conversation) => conversation.status !== "resolved",
  ),
  ingestionStatuses: knowledge.filter(
    (source) => source.status !== "ready",
  ),
  activity: [
    agents[0].activity[0],
    agents[2].activity[0],
    agents[3].activity[0],
    agents[5].activity[0],
  ],
  integrationSummary: [
    {
      label: "Connected",
      value: "3",
      change: "Stable",
      tone: "success",
    },
    {
      label: "Syncing",
      value: "1",
      change: "CRM schema refresh",
      tone: "neutral",
    },
    {
      label: "Needs attention",
      value: "1",
      change: "MCP Server",
      tone: "warning",
    },
  ],
  metrics: [
    {
      label: "Average first response",
      value: "3.2m",
      change: "-0.7m vs last week",
      tone: "success",
    },
    {
      label: "Resolution rate",
      value: "92%",
      change: "+4%",
      tone: "success",
    },
    {
      label: "Knowledge coverage",
      value: "84%",
      change: "+6 sources added",
      tone: "neutral",
    },
    {
      label: "Manager interventions",
      value: "5",
      change: "-2 vs yesterday",
      tone: "success",
    },
  ],
  alerts: [
    {
      title: "Support policy confidence is reduced",
      detail: "Refund Policy v3 is still processing. Support and Agent Manager are operating with partial coverage.",
      tone: "warning",
    },
    {
      title: "Private MCP connection is stale",
      detail: "No successful sync in 47 minutes. Internal reporting access may be degraded.",
      tone: "warning",
    },
  ],
  recommendations: [
    {
      title: "Review pricing queue first",
      detail: "Approving the open sales exception likely unlocks revenue faster than any other pending action.",
      tone: "success",
    },
    {
      title: "Assign a human owner to refund policy ingestion",
      detail: "That will reduce support hesitation and close three blocked conversations.",
    },
  ],
};

const analytics: AnalyticsData = {
  summary: [
    {
      label: "Conversation volume",
      value: "1,248",
      change: "+11% MoM",
      tone: "neutral",
    },
    {
      label: "Resolution rate",
      value: "92%",
      change: "+4% MoM",
      tone: "success",
    },
    {
      label: "Leads generated",
      value: "76",
      change: "+9 this month",
      tone: "success",
    },
    {
      label: "Knowledge gaps",
      value: "3",
      change: "-2 since last review",
      tone: "warning",
    },
  ],
  trends: [
    { label: "Mon", conversations: 156, responseMinutes: 4.2, resolutions: 91, leads: 8 },
    { label: "Tue", conversations: 174, responseMinutes: 3.8, resolutions: 94, leads: 11 },
    { label: "Wed", conversations: 162, responseMinutes: 3.5, resolutions: 92, leads: 10 },
    { label: "Thu", conversations: 183, responseMinutes: 3.1, resolutions: 95, leads: 14 },
    { label: "Fri", conversations: 191, responseMinutes: 3.3, resolutions: 93, leads: 16 },
  ],
  topAgents: [
    {
      agentId: "secretary-agent",
      name: "Mila Hart",
      role: "Secretary Agent",
      score: "9.6/10",
      output: "97% follow-through quality",
    },
    {
      agentId: "agent-manager",
      name: "Ava Mercer",
      role: "Agent Manager",
      score: "9.4/10",
      output: "Fast risk summarization",
    },
    {
      agentId: "sales-agent",
      name: "Nora Ellis",
      role: "Sales Agent",
      score: "9.3/10",
      output: "Strong lead qualification",
    },
  ],
  knowledgeGaps: [
    "Refund policy coverage is still processing for Support.",
    "Recruiting video transcript confidence is low in two sections.",
    "Customer Success needs refreshed launch playbooks for retail deployments.",
  ],
  recruiterPipeline: [
    { stage: "Sourced", count: 23 },
    { stage: "Screening", count: 11 },
    { stage: "Manager review", count: 5 },
    { stage: "Offer", count: 2 },
  ],
};

const billing: BillingData = {
  plan: "Enterprise Growth",
  renewalDate: "April 14, 2026",
  usage: [
    { label: "Active agents", value: "6 / 8", change: "2 available", tone: "neutral" },
    { label: "User seats", value: "14 / 20", change: "6 available", tone: "neutral" },
    { label: "Knowledge storage", value: "68 GB / 120 GB", change: "57% used", tone: "neutral" },
    { label: "Realtime actions", value: "428k / mo", change: "Within plan", tone: "success" },
  ],
  invoices: [
    { id: "inv-1048", date: "Mar 01, 2026", amount: "$3,480.00", status: "Paid" },
    { id: "inv-1041", date: "Feb 01, 2026", amount: "$3,480.00", status: "Paid" },
    { id: "inv-1034", date: "Jan 01, 2026", amount: "$3,120.00", status: "Paid" },
  ],
  paymentMethod: {
    brand: "Visa",
    last4: "4242",
    expiry: "08/28",
  },
};

const settings: SettingsData = {
  workspaceName: "Aigentics HQ",
  branding: "Enterprise navy palette with customer-safe email signature footer.",
  securitySummary: "SSO ready, MFA encouraged, approval logs retained for 180 days.",
  compliance: ["SOC 2 report placeholder", "Retention controls placeholder", "Audit export placeholder"],
  defaults: ["Agent approvals default to manager review", "Sensitive channels are human-visible by default"],
};

const support: SupportData = {
  resources: [
    {
      title: "Help center",
      detail: "Browse setup, training, governance, and integration guides.",
    },
    {
      title: "Contact support",
      detail: "Open a priority ticket or reach the enterprise support desk.",
    },
    {
      title: "Platform status",
      detail: "Placeholder link for status incidents and planned maintenance.",
    },
  ],
  onboardingChecklist: [
    "Hire your first core agents",
    "Connect Gmail or Slack",
    "Upload knowledge sources",
    "Review approval defaults",
    "Invite managers and human operators",
  ],
};

const account: AccountData = {
  name: "Oscar Fernandez",
  email: "oscar@example.com",
  title: "Workspace Admin",
  timezone: "America/Lima",
  sessions: ["MacBook Pro - Lima - Active now", "Chrome - New York - 2 days ago"],
  notifications: ["Approvals in app and email", "Integration failures in app", "Weekly executive digest"],
  connectedAccounts: ["Google Workspace", "Slack"],
};

export const workspaceSnapshot: WorkspaceSnapshot = {
  dashboard,
  agents,
  conversations,
  knowledge,
  integrations,
  users,
  notifications,
  analytics,
  billing,
  settings,
  support,
  account,
  currentUser: users[0],
};

export const hireableRoles = [
  {
    role: "Secretary Agent",
    description: "Coordinates executive schedules, inboxes, briefs, and follow-through.",
    useCases: ["Inbox triage", "Calendar orchestration", "Meeting briefs"],
    personality: "Polished, detail-oriented, and quietly proactive.",
    integrations: ["Gmail", "Calendar", "Docs", "Slack"],
    tasks: ["Prepare leadership brief", "Reschedule meetings", "Draft follow-up notes"],
  },
  {
    role: "Support Agent",
    description: "Handles inbound support conversations, triage, escalations, and policy-aware responses.",
    useCases: ["Shared inbox triage", "WhatsApp support", "Escalation handling"],
    personality: "Calm, empathetic, and disciplined under pressure.",
    integrations: ["Helpdesk", "Gmail", "Slack", "CRM"],
    tasks: ["Resolve onboarding issue", "Pause risky reply", "Route escalation"],
  },
  {
    role: "Sales Agent",
    description: "Qualifies demand, books meetings, follows up, and manages commercial context.",
    useCases: ["Lead qualification", "Pricing follow-up", "Demo booking"],
    personality: "Consultative, commercially sharp, and concise.",
    integrations: ["CRM", "Calendar", "Gmail", "Slack"],
    tasks: ["Qualify lead", "Draft recap", "Request pricing approval"],
  },
  {
    role: "Customer Success Agent",
    description: "Supports onboarding, adoption, renewal follow-up, and risk detection.",
    useCases: ["Onboarding check-ins", "Health monitoring", "Renewal prep"],
    personality: "Supportive, observant, and structured.",
    integrations: ["CRM", "Slack", "Docs", "Email"],
    tasks: ["Flag adoption risk", "Prepare renewal brief", "Draft success recap"],
  },
  {
    role: "Recruiter Agent",
    description: "Keeps hiring pipelines moving with candidate communication and scheduling discipline.",
    useCases: ["Screening coordination", "Interview scheduling", "Candidate follow-up"],
    personality: "Professional, organized, and prompt.",
    integrations: ["ATS", "Calendar", "Email"],
    tasks: ["Advance candidate", "Schedule panel", "Share interview brief"],
  },
  {
    role: "Agent Manager",
    description: "Supervises the workforce, surfaces risks, and coordinates recommendations across all agents.",
    useCases: ["Executive summaries", "Approval guidance", "Operational oversight"],
    personality: "Calm, strategic, and audit-friendly.",
    integrations: ["Analytics", "Slack", "Approvals", "Knowledge"],
    tasks: ["Summarize risk", "Recommend changes", "Monitor coverage"],
  },
] as const;

